[workspace]
members = ["crates/*"]

resolver = "3"

[workspace.package]
edition = "2024"
version = "0.1.0"

[workspace.dependencies]
serde = "1.0.217"
serde-wasm-bindgen = "0.6.5"
web-sys = { version = "0.3.77", features = ["console"] }
